CREATE TABLE IF NOT EXISTS t_activiteat (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeClasse INT(12) DEFAULT NULL,
	codeActivite INT(12) DEFAULT NULL,
	description VARCHAR(255) DEFAULT NULL,
	taux DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;