CREATE TABLE IF NOT EXISTS t_attestation (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	numeroDebut INT(12) DEFAULT NULL,
	numeroFin INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	dateReception DATE DEFAULT NULL,
	nombreAttestation INT(12) DEFAULT NULL,
	nombreUtilise INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;