CREATE TABLE IF NOT EXISTS t_branche (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(10) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	idCompagnie INT(9) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;