CREATE TABLE IF NOT EXISTS t_carteverte (
	id INT(11) NOT NULL AUTO_INCREMENT,
	dateEffet DATE DEFAULT NULL,
	dateExpiration DATE DEFAULT NULL,
	immatriculation VARCHAR(50) DEFAULT NULL,
	categorie VARCHAR(50) DEFAULT NULL,
	marque VARCHAR(50) DEFAULT NULL,
	numeroPolice VARCHAR(255) DEFAULT NULL,
	souscripteur VARCHAR(255) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;