CREATE TABLE IF NOT EXISTS t_defenserecours (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	codeSousClasse INT(9) DEFAULT NULL,
	puissanceFiscale INT(9) DEFAULT NULL,
	typeDefense VARCHAR(50) DEFAULT NULL,
	valeurDefense DECIMAL(12,2) DEFAULT NULL,
	formuleDefense INT(12) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;