CREATE TABLE IF NOT EXISTS t_tarifsassurancesfrontieres (
	id INT(11) NOT NULL AUTO_INCREMENT,
	typeUsage VARCHAR(50) DEFAULT NULL,
	periode INT(12) DEFAULT NULL,
	primeRC DECIMAL(12,2) DEFAULT NULL,
	taxes DECIMAL(12,2) DEFAULT NULL,
	primeDR DECIMAL(12,2) DEFAULT NULL,
	taxesDR DECIMAL(12,2) DEFAULT NULL,
	timbre DECIMAL(12,2) DEFAULT NULL,
	primeTotale DECIMAL(12,2) DEFAULT NULL,
	tauxPrimeRemorque DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;